# Generated by Django 6.1.1 on 2026-09-11 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_category_product_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
    ]
